### ISSUE TITLE
Chamadas de métodos com nome errado linha 61 e 62

### ISSUE THREAD

**Issue by felipephelype** [silviamuniz/blog_api#1]
https://github.com/silviamuniz/blog_api/blob/c468e207ed1c8257224e8ea47eeb1caa52caf742/config/initializers/devise_token_auth.rb#L61
o correto é config.default_confirm_**success**_url = 'http://localhost:4200/login'

https://github.com/silviamuniz/blog_api/blob/c468e207ed1c8257224e8ea47eeb1caa52caf742/config/initializers/devise_token_auth.rb#L63
o correto é default_password_**reset**_url = 'http://localhost:4200/reset-password'

**Comment by felipephelype** [comment]
A aplicação só subiu quando alterei localmente.

**Comment by silviamuniz** [comment]
Alterações feitas!
